# compose.offline.yml - Completely offline agent (emergency mode)
# Use with: docker compose -f compose.offline.yml up
#
# This mode provides ZERO network access - not even to allowlisted domains.
# Use for maximum isolation when reviewing suspicious code or testing.

services:
  agent:
    build:
      context: ../image
      dockerfile: Dockerfile
    image: sapphire-bee:latest
    container_name: agent_offline
    stdin_open: true
    tty: true

    # Environment - no API key needed in offline mode
    environment:
      - HOME=/home/claude
      - USER=claude
      - OFFLINE_MODE=true

    # No network at all
    network_mode: none

    # Mount project (can be direct or staging)
    volumes:
      - ${PROJECT_PATH:-./../project}:/project:rw

    # Security hardening
    read_only: true
    tmpfs:
      - /tmp:size=100M,mode=1777
      - /home/claude:size=500M,mode=0755,uid=1000,gid=1000
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

    # Resource limits
    deploy:
      resources:
        limits:
          memory: ${AGENT_MEMORY_LIMIT:-2G}
          cpus: "${AGENT_CPU_LIMIT:-2.0}"
          pids: 256
        reservations:
          memory: 256M

    # Working directory
    working_dir: /project

