# compose.base.yml - Base compose file with networks, DNS filter, and proxy services
# Does NOT include the agent container - that's in compose.direct.yml or compose.staging.yml

name: claude-godot-sandbox

networks:
  # Internal network for sandbox - no direct internet access
  sandbox_net:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.100.1.0/24
          gateway: 10.100.1.1

  # Egress network for proxy containers to reach internet
  egress_net:
    driver: bridge

services:
  # ===========================================
  # DNS Filter (CoreDNS)
  # ===========================================
  dnsfilter:
    image: coredns/coredns:1.11.1
    container_name: dnsfilter
    restart: unless-stopped
    command: ["-conf", "/etc/coredns/Corefile"]
    volumes:
      - ../configs/coredns/Corefile:/etc/coredns/Corefile:ro
      - ../configs/coredns/hosts.allowlist:/etc/coredns/hosts.allowlist:ro
    networks:
      sandbox_net:
        ipv4_address: 10.100.1.2
    # Only on sandbox_net - no internet access needed
    # Note: CoreDNS image is distroless (no shell, no curl/wget) - healthcheck not possible
    # The container exposes :8080/health but there's no way to query it from inside
    # Rely on restart: unless-stopped and depends_on: service_started
    # Security hardening
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true

  # ===========================================
  # Proxy: github.com
  # ===========================================
  proxy_github:
    image: nginx:1.25-alpine
    container_name: proxy_github
    restart: unless-stopped
    volumes:
      - ../configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../configs/nginx/proxy_github.conf:/etc/nginx/conf.d/stream.conf:ro
      - ../configs/nginx/empty.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      sandbox_net:
        ipv4_address: 10.100.1.10
      egress_net:
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true

  # ===========================================
  # Proxy: raw.githubusercontent.com
  # ===========================================
  proxy_raw_githubusercontent:
    image: nginx:1.25-alpine
    container_name: proxy_raw_githubusercontent
    restart: unless-stopped
    volumes:
      - ../configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../configs/nginx/proxy_raw_githubusercontent.conf:/etc/nginx/conf.d/stream.conf:ro
      - ../configs/nginx/empty.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      sandbox_net:
        ipv4_address: 10.100.1.11
      egress_net:
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true

  # ===========================================
  # Proxy: codeload.github.com
  # ===========================================
  proxy_codeload_github:
    image: nginx:1.25-alpine
    container_name: proxy_codeload_github
    restart: unless-stopped
    volumes:
      - ../configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../configs/nginx/proxy_codeload_github.conf:/etc/nginx/conf.d/stream.conf:ro
      - ../configs/nginx/empty.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      sandbox_net:
        ipv4_address: 10.100.1.12
      egress_net:
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true

  # ===========================================
  # Proxy: docs.godotengine.org
  # ===========================================
  proxy_godot_docs:
    image: nginx:1.25-alpine
    container_name: proxy_godot_docs
    restart: unless-stopped
    volumes:
      - ../configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../configs/nginx/proxy_godot_docs.conf:/etc/nginx/conf.d/stream.conf:ro
      - ../configs/nginx/empty.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      sandbox_net:
        ipv4_address: 10.100.1.13
      egress_net:
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true

  # ===========================================
  # Proxy: api.anthropic.com
  # ===========================================
  proxy_anthropic_api:
    image: nginx:1.25-alpine
    container_name: proxy_anthropic_api
    restart: unless-stopped
    volumes:
      - ../configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../configs/nginx/proxy_anthropic_api.conf:/etc/nginx/conf.d/stream.conf:ro
      - ../configs/nginx/empty.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      sandbox_net:
        ipv4_address: 10.100.1.14
      egress_net:
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true

